# Generated by Django 5.0.3 on 2024-03-10 14:15

import django.db.models.deletion
import tinymce_4.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de couverture de l'article",
                null=True,
                upload_to="article_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce_4.fields.TinyMCEModelField(
                help_text="Contenu de l'article au format HTML", verbose_name="Contenu"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_published",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date de publication de l'article"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(help_text="Titre de l'article", max_length=255),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="content",
            field=models.TextField(help_text="Contenu du message sur le forum"),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date de publication du message sur le forum",
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="title",
            field=models.CharField(
                help_text="Titre du message sur le forum", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="forumpost",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui a posté sur le forum",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
