# Generated by Django 5.0.3 on 2024-03-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                help_text="Image du cours", upload_to="course_images/"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(help_text="Description du cours"),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration_in_minutes",
            field=models.IntegerField(help_text="Durée du cours en minutes"),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                help_text="Niveau du cours",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(help_text="Titre du cours", max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_url",
            field=models.URLField(help_text="URL de la vidéo du cours"),
        ),
        migrations.AlterField(
            model_name="energyexchange",
            name="date_shared",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date et heure de l'échange"
            ),
        ),
        migrations.AlterField(
            model_name="energyexchange",
            name="energy_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Quantité d'énergie échangée", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="energyexchange",
            name="exchange_type",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Sell", "Sell"), ("Share", "Share")],
                help_text="Type d'échange (Achat, Vente, Partage)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="energyexchange",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur participant à l'échange d'énergie",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="energymarketplace",
            name="available_quantity",
            field=models.IntegerField(help_text="Quantité disponible sur le marché"),
        ),
        migrations.AlterField(
            model_name="energymarketplace",
            name="product",
            field=models.OneToOneField(
                help_text="Produit associé sur le marché de l'énergie",
                on_delete=django.db.models.deletion.CASCADE,
                to="produits.product",
            ),
        ),
        migrations.AlterField(
            model_name="energymarketplace",
            name="seller",
            field=models.ForeignKey(
                help_text="Vendeur sur le marché de l'énergie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="energy_marketplace_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Description du produit"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Disponibilité du produit"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Nom du produit", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Prix du produit", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                help_text="Image du produit", upload_to="product_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_available",
            field=models.IntegerField(
                default=0, help_text="Quantité disponible en stock"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorship",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date et heure de la recommandation"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorship",
            name="referred_user",
            field=models.ForeignKey(
                help_text="Utilisateur recommandé",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorship",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui fait la recommandation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
